name: eb-deploy

on:
    push:
        branches:
            - 'ecs-deploy'

jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout source code
              uses: actions/checkout@v2

            - name: Create env file
              run: |
                  touch .env
                  echo "NODE_ENV=prod" >> .env
                  echo "PORT=$PORT" >> .env
                  echo "GH_TOKEN=$GH_TOKEN" >> .env
                  echo "DISCORD_TOKEN=$DISCORD_TOKEN" >> .env
                  echo "MONGO_URI=$MONGO_URI" >> .env
              env:
                  PORT: ${{ secrets.PORT }}
                  GH_TOKEN: ${{ secrets.GH_TOKEN }}
                  DISCORD_TOKEN: ${{ secrets.DISCORD_TOKEN }}
                  MONGO_URI: ${{ secrets.MONGO_URI }}

            - name: Generate deployment package
              run: zip -r ${{ github.sha }}.zip . -x "*.git*" node_modules

            - name: Deploy to EB
              uses: einaregilsson/beanstalk-deploy@v20
              with:
                  aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
                  aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                  application_name: mashong-discord-bot
                  environment_name: Mashongdiscordbot-env
                  version_label: ${{ github.sha }}
                  version_description: ${{ github.event.head_commit.message }}
                  region: ap-northeast-2
                  deployment_package: ${{ github.sha }}.zip
